#!/usr/bin/env node

'use strict';

/* globals process exports */
/* eslint-disable lines-around-comment */

var fn = function(obj, accumaltedKey) {
  var keys = Object.keys(obj);
  var result = [];

  keys.forEach((key) => {
    var val = obj[key];
    var acKey = accumaltedKey + '.' + key;

    if (val !== null && typeof val === 'object' && !Array.isArray(val)) {
      result = result.concat(fn(val, acKey));
    } else {
      result = result.concat([ {key: acKey, value: val} ]);
    }
  });

  return result;
};

function toPath(obj) {
  var inPaths = {};

  if (obj === null || typeof obj !== 'object' || Array.isArray(obj)) {
    return obj;
  }

  fn(obj, '').forEach((pair) => {
    inPaths[pair.key.slice(1)] = pair.value;
  });
  return (inPaths);
}

exports.toPath = toPath;
